apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: cloth-mini-app

# apiVersion: v1
# kind: Service
# metadata:
#   name: postgresql
# spec:
#   type: ClusterIP
#   ports:
#     - port: 5232
#       targetPort: 5230
#   selector:
#     app: postgresql