global:
  env: "dev"
  namespace: "mini-app"

postgresql:
  auth:
    replicationPassword: admin
    postgresPassword: admin ## main user
    username: admin ## custom username
    password: admin
    database: storage
  primary:
    initdb:
      scripts:
        init-database.sh: |
          #!/bin/bash
          set -e

          export PGPASSWORD="admin"

          psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "storage" <<-EOSQL
              CREATE DATABASE users;
              GRANT USAGE ON SCHEMA public TO admin;
              GRANT CREATE ON SCHEMA public TO admin;
              GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
              GRANT ALL PRIVILEGES ON DATABASE storage TO admin;
              GRANT ALL PRIVILEGES ON DATABASE users TO admin;
          EOSQL

minio:
  auth:
    rootUser: "admin"
    rootPassword: "minio123"

kafka:
  zookeeper:
    enabled: false
  listeners:
    client:
      protocol: "PLAINTEXT"
    controller:
      protocol: "PLAINTEXT"
    external:
      protocol: "PLAINTEXT"
  securityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  controller:
    replicaCount: 1
    quorumVoters: "0@kafka-0.kafka-headless.default.svc.cluster.local:9093"
  broker:
    replicaCount: 1

services:
  clothMiniApp:
    enabled: true
    replicas: 3
    ports:
      containerPort: 8080
      servicePort: 80
  telegram:
    enebled: true
    replicas: 1
    ports:
      containerPort: 443
      servicePort: 443
  notifications:
    enebled: true
    replicas: 2
    ports:
      containerPort: 8084

ingress:
  enabled: false